import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('language') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => prev === 'fr' ? 'en' : 'fr');
  };

  const t = (key) => {
    const translations = {
      fr: {
        'home': 'ACCUEIL',
        'gallery': 'GALERIE',
        'jury': 'JURY',
        'sponsors': 'SPONSORS',
        'submit': 'Soumettre un film',
        'logout': 'Déconnexion',
        'login': 'Connexion',
        'hero_title': 'FESTIVAL MARS AI',
        'hero_subtitle': 'Où l\'IA rencontre le cinéma',
        'discover': 'Découvrir',
        'about': 'À Propos',
        'about_title': 'À propos de Mars AI',
        'about_desc': 'Un festival innovant célébrant la fusion entre l\'intelligence artificielle et le cinéma. Découvrez comment l\'IA transforme la créativité filmique.',
        'close': 'Fermer',
        'categories': 'Catégories',
        'awards': 'Récompenses',
        'awards_title': 'Les Récompenses du Festival',
        'partners': 'Partenaires',
        'contact': 'Contact',
        'year': '2026',
        'sci_fi': 'SCI-FI',
        'horror': 'HORREUR',
        'action': 'ACTION',
        'drama': 'DRAME',
        'thriller': 'THRILLER',
        'documentary': 'DOCUMENTAIRE',
        'animation': 'ANIMATION',
        'history': 'HISTOIRE',
        'footer_description': 'Festival Sci-Fi & IA : films, jury, sponsors, créations et exploration visuelle. Mobile-first, rapide et moderne.',
        'footer_navigation': 'NAVIGATION',
        'footer_home': 'Accueil',
        'footer_gallery': 'Galerie',
        'footer_jury': 'Jury',
        'footer_sponsors': 'Sponsors',
        'footer_submission': 'Soumission',
        'footer_infos': 'INFOS',
        'footer_location': '📍 Paris / Mars (virtuel)',
        'footer_projections': '🎬 Projections & concours',
        'footer_ai': '🤖 IA créative',
        'footer_newsletter': 'NEWSLETTER',
        'footer_newsletter_desc': 'Reçois les actus, appels à films, et annonces du festival.',
        'footer_email_placeholder': 'ton@email.com',
        'footer_subscribe': 'S\'inscrire',
        'footer_spam_notice': 'Zéro spam. Désinscription en 1 clic.',
        'footer_copyright': 'Tous droits réservés.',
        'footer_legal': 'Mentions légales',
        'footer_privacy': 'Confidentialité',
        'login_title': 'CONNEXION',
        'login_email': 'Adresse mail',
        'login_password': 'Mot de passe',
        'login_button': 'Connexion',
        'login_google': 'Se connecter avec Google',
        'login_error': 'Erreur de connexion',
        'login_forgot': 'Mot de passe oublié ?',
        'gallery_title': 'Galerie des Films',
        'gallery_subtitle': 'Découvrez les films du Festival Mars AI',
        'gallery_search': 'Rechercher un film...',
        'gallery_loading': 'Chargement des films...',
        'gallery_error': 'Impossible de charger les films. Veuillez réessayer plus tard.',
        'gallery_no_results': 'Aucun film ne correspond à votre recherche.',
        'gallery_by': 'Par',
        'gallery_no_synopsis': 'Pas de synopsis',
        'gallery_unknown_duration': 'Durée inconnue',
        'gallery_prev': 'Précédent',
        'gallery_next': 'Suivant',
        'gallery_total': 'film(s) au total',
        'detail_director': 'Réalisé par',
        'detail_genres': 'Genres :',
        'detail_ai_class': 'Classification IA :',
        'detail_ai_tools': 'Outils IA utilisés :',
        'detail_language': 'Langue :',
        'detail_duration': 'Durée',
        'detail_minutes': 'minutes',
        'detail_seconds': 'secondes',
        'detail_subtitles': 'Sous-titres :',
        'detail_no_synopsis_available': 'Pas de synopsis disponible',
        'detail_english_synopsis': 'Synopsis anglais :',
        'gallery_images': 'Galerie d\'images',
        'status': 'Statut',
        'detail_pending': 'En attente',
        'detail_approved': 'Approuvé',
        'detail_rejected': 'Rejeté',
        'detail_themes': 'Thèmes',
        'detail_synopsis': 'Synopsis',
        'detail_english_version': 'Voir la version anglaise →',
        'detail_less': '← Voir moins',
        'detail_methodology': 'Méthodologie IA',
        'detail_team': 'Équipe de production',
        'detail_collaborators': 'Collaborateurs',
        'detail_gallery': 'Galerie',
        'detail_similar': 'Films similaires',
        'detail_loading': 'Chargement du film...',
        'detail_error': 'Impossible de charger les détails du film',
        'detail_like': 'Aimer ce film',
        'detail_share': 'Partager ce film',
        'detail_back': 'Retour à la galerie',
        'forgot_title': 'Reset-password',
        'forgot_email': 'Adresse mail',
        'forgot_submit': 'Valider →',
        'forgot_back': 'Retour à la page de connexion',
        'dashboard_user_title': 'Gestion des utilisateurs',
        'dashboard_user_add': 'Ajouter un utilisateur',
        'dashboard_user_admin': 'Admin',
        'dashboard_user_jury': 'Jury',
        'dashboard_user_moderator': 'Modérateur',
        'dashboard_user_see': 'Voir',
        'dashboard_user_edit': 'Modifier profil',
        'dashboard_user_delete': 'Supprimer',
        'dashboard_user_fullname': 'Nom complet :',
        'dashboard_user_email': 'Email :',
        'dashboard_user_role': 'Rôle :',
        'dashboard_user_cancel': 'Annuler',
        'dashboard_user_save': 'Enregistrer',
        'dashboard_user_saving': 'Enregistrement...',
        'dashboard_user_confirm_delete': 'Êtes-vous sûr de vouloir supprimer',
        'dashboard_user_irreversible': '? Cette action est irréversible.',
        'dashboard_user_success': 'Utilisateur supprimé avec succès',
        'dashboard_user_updated': 'Utilisateur mis à jour avec succès !',
        'dashboard_user_invited': 'Invitation envoyée avec succès à',
        'dashboard_user_sending': 'Envoi en cours...',
        'dashboard_user_add_invite': 'Ajouter et inviter',
        'dashboard_user_column_user': 'Utilisateur',
        'dashboard_user_column_role': 'Rôle',
        'dashboard_user_column_actions': 'Actions',
        'dashboard_user_error': 'Erreur',
        'dashboard_user_error_update': 'Impossible de mettre à jour l\'utilisateur',
        'dashboard_user_error_delete': 'Impossible de supprimer l\'utilisateur',
        'dashboard_user_error_create': 'Impossible de créer l\'utilisateur',
        'dashboard_title': 'TABLEAU ADMIN',
        'dashboard_subtitle': 'Vue générale de l\'activité et gestion des soumissions',
        'dashboard_admin': 'Administrateur',
        'dashboard_function': 'Fonction',
        'reset_title': 'RESET-PASSWORD',
        'reset_password': 'Mot de passe :',
        'reset_confirm': 'Confirmation du mot de passe :',
        'reset_button': 'RÉINITIALISER',
        'reset_back': 'Retour à la connexion',
        'reset_no_token': 'Token manquant dans l\'URL.',
        'reset_mismatch': 'Les mots de passe ne correspondent pas.',
        'reset_success': 'Mot de passe réinitialisé avec succès.',
        'notfound_404': '404',
        'notfound_title': 'Page introuvable',
        'notfound_message': 'La page que vous cherchez a disparu dans une orbite inconnue. Revenez a la station.',
        'notfound_home': 'Retour accueil',
        'jury_loading': 'Chargement du film...',
        'jury_not_found': 'Film introuvable',
        'jury_back': 'Retour à la sélection',
        'jury_official': 'Festival Mars AI — Sélection officielle',
        'jury_fr': '🇫🇷 FR',
        'jury_en': '🇬🇧 EN',
        'jury_evaluate': 'VOTRE ÉVALUATION',
        'jury_evaluate_desc': 'Notez ce film et partagez votre avis professionnel',
        'jury_like': 'J\'aime',
        'jury_discuss': 'À discuter',
        'jury_dislike': 'J\'aime pas',
        'jury_comment': 'Commentaire',
        'jury_optional': '(optionnel)',
        'jury_comment_placeholder': 'Partagez vos impressions, critiques constructives ou remarques sur ce film...',
        'jury_submit': 'Soumettre mon évaluation',
        'jury_submitting': 'Soumission en cours...',
        'jury_success': 'Vote enregistré avec succès',
        'jury_saved': 'Votre évaluation a été sauvegardée',
        'jury_edit': 'Modifier mon vote',
        'jury_error': 'Impossible de charger le film',
        'gestion_films_title': 'Gestion films',
        'gestion_films_distribution': 'DISTRIBUTION MOVIES',
        'gestion_films_subtitle': 'Gérez l\'intégralité des soumissions, approuvez ou rejetez les films soumis.',
        'gestion_films_admin_label': 'ADMINISTRATEUR',
        'gestion_films_email_label': 'EMAIL DU RÉALISATEUR',
        'gestion_films_role_label': 'MODÉRATEUR',
        'gestion_films_column_poster': 'Affiche',
        'gestion_films_column_title': 'Titre',
        'gestion_films_column_director': 'Réalisateur',
        'gestion_films_column_status': 'Statut',
        'gestion_films_column_date': 'Date',
        'gestion_films_column_actions': 'Actions',
        'gestion_films_search': 'Rechercher un film…',
        'gestion_films_all': 'Tous',
        'gestion_films_valid': 'Validé',
        'gestion_films_pending': 'En attente',
        'gestion_films_refused': 'Refusé',
        'gestion_films_loading': 'Chargement des films...',
        'gestion_films_submitted': 'Film soumis',
        'gestion_films_valid_tag': 'VALIDÉ',
        'gestion_films_pending_tag': 'EN ATTENTE',
        'gestion_films_refused_tag': 'REFUSÉ',
        'gestion_films_approve': 'Approuver',
        'gestion_films_reject': 'Rejeter',
        'gestion_films_details': 'Détails',
        'gestion_films_page': 'Page',
        'gestion_films_all_selected': 'Tous les films sont sélectionnés',
        'gestion_films_none_selected': 'Aucun film sélectionné',
        'gestion_films_poster': 'Affiche',
        'gestion_films_approved_ok': 'Film approuvé ✓',
        'gestion_films_rejected_ok': 'Film rejeté',
        'gestion_films_featured': 'Film mis en avant',
        'gestion_films_unfeatured': 'Retiré de la mise en avant',
        'gestion_films_status_distribution': 'Répartition des statuts',
        'gestion_films_status': 'Statut',
        'gestion_films_approval_progress': 'Progression des approbations',
        'gestion_films_approved': 'Approuvés',
        'gestion_films_pending_review': 'En attente d\'examen',
        'gestion_films_submission_trend': 'Tendance des soumissions',
        'gestion_films_total_submitted': 'Total soumis',
        'gestion_films_approval_rate': 'Taux d\'approbation',
        'gestion_films_rejection_rate': 'Taux de rejet',
        'jury_dist_title': 'Distribution jury',
        'jury_dist_subtitle': 'Assignez les membres du jury pour l\'évaluation des films',
        'jury_dist_description': 'Gérez l\'assignation des jurés et leurs sélections pour évaluer les films.',
        'jury_dist_admin_management': 'Gestion Admin',
        'jury_dist_admin_label': 'ADMINISTRATEUR',
        'jury_dist_email_label': 'EMAIL',
        'jury_dist_role_label': 'RÔLE',
        'jury_dist_loading': 'Chargement...',
        'jury_dist_vote_distribution': 'Répartition des votes',
        'jury_dist_votes_category': 'Votes',
        'jury_dist_like': 'J\'aime',
        'jury_dist_discuss': 'À discuter',
        'jury_dist_dislike': 'N\'aime pas',
        'jury_dist_global_progress': 'Progrès global',
        'jury_dist_completed': 'Complété',
        'jury_dist_remaining': 'Restant',
        'jury_dist_progress': 'Progrès',
        'jury_dist_active_jurors': 'Jurés actifs',
        'competition_anim_title': 'Espace Administrateur',
        'competition_anim_subtitle': 'Compétition Animation',
        'competition_anim_desc': 'Gérez les films sélectionnés et les jurés assignés pour cette catégorie',
        'competition_films': '1. Sélection des Films',
        'competition_available': 'Films Disponibles',
        'competition_selected': 'Films Sélectionnés',
        'competition_all_films_selected': 'Tous les films sont sélectionnés',
        'competition_no_films': 'Aucun film sélectionné',
        'competition_jury': '2. Assignation des Jurés',
        'competition_jury_available': 'Membres Disponibles',
        'competition_jury_assigned': 'Jurés Assignés',
        'competition_all_jury_assigned': 'Tous les jurés sont assignés',
        'competition_no_jury': 'Aucun juré assigné',
        'jury_management': 'Gestion Admin',
        'jury_management_title': 'GESTION JURYS',
        'jury_management_desc': 'Assignation des jurés et leurs sélections pour l\'évaluation des films.',
        // JuryTab Component Keys FR
        'jury_form_email_placeholder': 'Email',
        'jury_form_specialty_placeholder': 'Spécialité',
        'jury_form_role_jury': 'Membre du Jury',
        'jury_form_role_lead': 'Leader du Jury',
        'jury_form_role_moderator': 'Modérateur',
        'jury_add_button': '✅ Ajouter',
        'jury_cancel_button': '✖️ Annuler',
        'jury_unspecified': 'Non spécifié',
        'jury_progress_label': 'Progression',
        'jury_approved_label': 'Approuvés',
        'jury_rejected_label': 'Rejetés',
        'jury_pending_label': 'À discuter',
        'jury_approval_label': 'Approbation',
        'jury_role_leader': '⭐ Leader',
        'jury_role_moderator': '⚖️ Mod',
        'jury_role_member': '📋 Jury',
        'jury_summary_title': '📧 Résumé des Membres',
        'jury_table_name': 'Nom',
        'jury_table_role': 'Rôle',
        'jury_table_progress': 'Progression',
        'jury_table_approved': '✅ Approuvés',
        'jury_table_rejected': '❌ Rejetés',
        'jury_table_approval': 'Approbation',
        'jury_role_moderator_full': '⚖️ Modérateur',
        'jury_specialty_creative_ai': 'IA Créative',
        'jury_specialty_video_production': 'Production Vidéo',
        'jury_stats_title': 'Statistiques Globales',
        'jury_jury_members_label': 'Membres du jury',
        'jury_films_evaluate_label': 'Films à évaluer',
        'jury_total_progress_label': 'Progression totale',
        'jury_approved_films_label': 'Films approuvés',
        'jury_members_section_title': '👥 Membres du Jury',
        'jury_add_member_button': '+ Ajouter un membre',
        'jury_notes': 'Notas du Jury',
        'jury_notes_title': 'Notes d\'Évaluation du Jury',
        'jury_notes_subtitle': 'Consultez les évaluations et notes des membres du jury',
        // Jury Page Keys
        'jury_page_loading': 'Chargement des jurys...',
        'jury_page_error': 'Impossible de charger les jurys',
        'jury_page_title': 'Le Grand Jury',
        'jury_page_presidency': 'Présidence du Festival',
        'jury_page_all_filters': 'Tous',
        'jury_page_filters_cinema': 'Cinéma',
        'jury_page_filters_ai': 'IA',
        'jury_page_filters_design': 'Design',
        'jury_page_anonymous': 'Membre Anonyme',
        'jury_page_expert': 'Expert Festival',
        'jury_page_details_button': 'Détails Jury',
        'jury_page_official_record': 'Fiche Officielle',
        'jury_page_jury_id': 'Identifiant Jury',
        'jury_page_accredited': 'Membre accrédité sous le numéro #{id}',
        'jury_page_registered': 'Inscrit le :',
        'sponsors_title': 'Nos partenaires',
        'sponsors_intro': 'Le Mars AI Festival remercie ses sponsors pour leur soutien dans la promotion de la créativité basée sur l\'intelligence artificielle.',
        'sponsors_gold': 'Sponsors Or',
        'sponsor_gold_1': 'Sponsor Or 1',
        'sponsor_gold_1_desc': 'Leader en solutions IA créatives',
        'sponsor_gold_2': 'Sponsor Or 2',
        'sponsor_gold_2_desc': 'Innovateurs dans la technologie vidéo',
        'sponsors_silver': 'Sponsors Argent',
        'sponsor_silver_1': 'Sponsor Argent 1',
        'sponsor_silver_2': 'Sponsor Argent 2',
        'sponsor_silver_3': 'Sponsor Argent 3',
        'become_sponsor': 'Devenir sponsor',
        'become_sponsor_desc': 'Intéressé par le sponsoring du Mars AI Festival ? Contactez-nous pour en savoir plus sur les opportunités de partenariat.',
        'contact_us': 'Nous contacter',
        // Film Detail Page Keys
        'film_detail_loading': 'Chargement du film...',
        'film_detail_error': 'Impossible de charger les détails du film',
        'film_detail_back': 'Retour à la galerie',
        'film_detail_directed_by': 'Réalisé par',
        'film_detail_like': 'Aimer ce film',
        'film_detail_share': 'Partager ce film',
        'film_detail_duration': 'Durée',
        'film_detail_language': 'Langue',
        'film_detail_ai': 'IA',
        'film_detail_status': 'Statut',
        'film_detail_themes': 'Thèmes',
        'film_detail_synopsis': 'Synopsis',
        'film_detail_see_less': '← Voir moins',
        'film_detail_see_english': 'Voir la version anglaise →',
        'film_detail_methodology': 'Méthodologie IA',
        'film_detail_tools_used': 'Outils utilisés:',
        'film_detail_team': 'Équipe de production',
        'film_detail_director': 'Réalisateur',
        'film_detail_gallery': 'Galerie',
        'film_detail_related': 'Films similaires',
        'film_detail_video_title': 'Vidéo du film',
        'film_detail_status_pending': 'En attente',
        'film_detail_status_approved': 'Approuvé',
        'film_detail_status_rejected': 'Rejeté',
        'film_detail_na': 'N/A',
        // Admin Header Keys
        'admin_dashboard': 'Tableau de bord',
        'admin_films': 'Films',
        'admin_jury': 'Jury',
        'admin_config': 'Configuration',
        'admin_logout': 'Déconnexion',
        'admin_moderator': 'MODÉRATEUR',
        'admin_role': 'Rôle',
        // Dashboard Tab Keys
        'dashboard_total_films': 'Total Films',
        'dashboard_total_jury': 'Total Jury',
        'dashboard_approved_label': 'Approuvés',
        // Films Management Keys
        'films_management': 'Gestion des Films',
        'films_no_films': 'Aucun film pour le moment',
        'films_management_title': 'Gestion des Films',
        // Configuration Keys
        'config_title': 'Configuration',
        'config_settings': 'Paramètres de configuration',
        'config_general': 'Paramètres Généraux',
        'config_festival_name': 'Nom du Festival',
        'config_festival_dates': 'Dates du Festival',
        'config_save': 'Enregistrer',
        'config_saved': 'Configuration enregistrée',
        // Events Tab Keys
        'events_title': 'Événements',
        'events_no_events': 'Aucun événement pour le moment',
        'events_add_event': 'Ajouter un événement',
        // Results Tab Keys
        'results_title': 'Résultats',
        'results_winners': 'Gagnants',
        'results_categories': 'Catégories',
        // Language Toggle
        'lang_fr': '🇫🇷 FR',
        'lang_en': '🇬🇧 EN',
        // Common Admin Actions
        'action_add': 'Ajouter',
        'action_edit': 'Modifier',
        'action_delete': 'Supprimer',
        'action_save': 'Enregistrer',
        'action_cancel': 'Annuler',
        'action_back': 'Retour',
        'action_confirm': 'Confirmer',
        'action_loading': 'Chargement...',
        // Modal Keys
        'modal_confirm_delete': 'Êtes-vous sûr ?',
        'modal_confirm_delete_text': 'Cette action est irréversible.',
        'modal_yes': 'Oui',
        'modal_no': 'Non',
        'modal_close': 'Fermer',
        // Table Headers
        'table_name': 'Nom',
        'table_email': 'Email',
        'table_role': 'Rôle',
        'table_status': 'Statut',
        'table_actions': 'Actions',
        'table_date': 'Date',
        // Validation Messages
        'error_required': 'Ce champ est requis',
        'error_email': 'Email invalide',
        'error_password_mismatch': 'Les mots de passe ne correspondent pas',
        'success_saved': 'Enregistrement réussi',
        'success_deleted': 'Suppression réussie',
        'success_updated': 'Mise à jour réussie',
        // JuryTab Additional Keys
        'jury_tab_global_stats': 'Statistiques Globales',
        'jury_tab_members': 'Membres du Jury',
        'jury_tab_add_member': '+ Ajouter un membre',
        'jury_tab_summary': 'Résumé des Membres',
        'jury_tab_email': 'Email',
        'jury_tab_full_name': 'Nom complet',
        'jury_tab_role_option': 'Jury',
        'jury_tab_loading': 'Chargement des jurys...',
        'jury_tab_add_button': 'Ajouter',
        'jury_tab_cancel_button': 'Annuler',
        'jury_tab_in_progress': 'En cours...',
        'jury_tab_films_to_evaluate': 'Films à évaluer',
        'jury_tab_total_progress': 'Progression totale',
        'jury_tab_global_decisions': 'Décisions globales',
        'jury_tab_liked': 'Aimé',
        'jury_tab_disliked': 'Pas aimé',
        'jury_tab_to_discuss': 'A discuter',
        'jury_tab_leader': 'Leader',
        'jury_tab_moderator': 'Modérateur',
        'jury_tab_jury': 'Jury',
        'jury_tab_specialty': 'Spécialité',
        'jury_tab_progress': 'Progression',
        'jury_tab_approval_rate': 'Approbation',
        'jury_tab_no_specialty': '-',
        // Header Keys
        'header_dashboard': 'Dashboard',
        'header_theme': 'Thème',
        'header_mode': 'Mode',
        'dashboard_jury_films_assigned': 'Films assignés',
        'dashboard_jury_like': 'J\'aime',
        'dashboard_jury_dislike': 'J\'aime pas',
        'dashboard_jury_discuss': 'À discuter',
        'dashboard_jury_my_playlists': 'Mes Playlists',
        'dashboard_jury_select_playlist': 'Sélectionnez une playlist pour consulter les vidéos',
        'dashboard_jury_loading': 'Chargement des playlists...',
        'dashboard_jury_error_loading': 'Impossible de charger les données',
        'dashboard_jury_unknown_director': 'Réalisateur inconnu',
        'admin_space': 'Espace Administrateur',
        'admin_dashboard_title': 'Tableau administrateur',
        'admin_dashboard_subtitle': 'Vue générale de l\'activité de la plateforme',
        'dashboard_submissions': 'Soumissions',
        'dashboard_statistics_approved': 'Approuvés',
        'dashboard_statistics_rejected': 'Rejetés',
        'dashboard_statistics_pending': 'En attente',
        'dashboard_evolution_title': 'Évolution des soumissions',
        'dashboard_evolution_subtitle': 'Statistiques sur les 8 dernières semaines',
        'dashboard_categories_title': 'Répartition des catégories',
        'dashboard_users_management': 'Gestion des utilisateurs',
        'dashboard_users_button': 'Voir les utilisateurs',
        'dashboard_finalists_selection': 'Selection des finalistes',
        'dashboard_finalists_button': 'Gérer les finalistes',
        'films_no_results': 'Aucun film trouvé',
        'films_no_results_search': 'pour',
        'badge_valid': 'VALIDÉ',
        'badge_pending': 'EN ATTENTE',
        'badge_rejected': 'REFUSÉ',
        'button_approve': 'Approuver',
        'button_reject': 'Rejeter',
        'button_details': 'Détails',
        'films_featured': 'Film mis en avant',
        'films_unfeatured': 'Retiré de la mise en avant',
        'notifictions_error_loading': 'Erreur lors du chargement des films',
        'error_moderation': 'Erreur lors de la modération du film',
        'toast_approved': 'Film approuvé ✓',
        'toast_rejected': 'Film rejeté',
        'config_home_title': 'Configuration Home',
        'config_home_desc': 'Gérez les sections visibles sur la page d\'accueil publique',
        'config_playlists_title': 'Sélections de films du festival',
        'config_assign_title': 'Assigner Films & Jury',
        'config_assign_desc': 'Associez des films et membres du jury à vos playlists',
        'config_film_singular': 'film',
        'config_film_plural': 'films',
        'config_jury_singular': 'membre',
        'config_jury_plural': 'membres jury',
        'notation_loading': 'Chargement du film...',
        'notation_back': 'Retour',
        'notation_back_selection': 'Retour à la sélection',
        'notation_your_evaluation': 'VOTRE ÉVALUATION',
        'notation_comment': 'Commentaire',
        'notation_submit': 'Soumettre mon évaluation',
        'notation_saved_message': 'Votre évaluation a été sauvegardée et ne peut pas être modifiée',
        'notation_error_submit': 'Erreur lors de la soumission du vote. Veuillez réessayer.',
        'notation_director': 'Réalisateur',
        'notation_duration': 'Durée',
        'notation_contact': 'Contact',
        'notation_location': 'Localisation',
        'notation_production_year': 'Année de production',
        'notation_themes': 'Thèmes',
        'notation_synopsis': 'Synopsis',
        'notation_watch_film': 'Regarder le film',
        'notation_official_selection': 'Festival Mars AI — Sélection officielle',
        'notation_evaluation_subtitle': 'Notez ce film et partagez votre avis professionnel',
        'notation_comment_placeholder': 'Partagez vos impressions, critiques constructives ou remarques sur ce film...',
        'notation_vote_success': 'Vote enregistré avec succès',
        'notation_vote_like': "J'aime",
        'notation_vote_discuss': 'À discuter',
        'notation_vote_dislike': "J'aime pas",
        // FAQ Page Keys (French)
        'faq_title': 'Questions Fréquentes',
        'faq_subtitle': 'Trouvez des réponses aux questions les plus courantes sur le festival, les soumissions et le fonctionnement de la plateforme Mars AI.',
        'faq_q1': "Qu'est-ce que Mars AI ?",
        'faq_a1': "Mars AI est une plateforme dédiée à la création cinématographique assistée par intelligence artificielle. Nous organisons des festivals, des concours et offrons une vitrine pour les créateurs utilisant l'IA dans leurs œuvres.",
        'faq_q2': 'Comment soumettre un film ?',
        'faq_a2': "Pour soumettre un film, vous devez créer un compte, vous connecter, puis cliquer sur 'Soumission' dans le menu. Remplissez le formulaire avec les détails de votre œuvre et le lien vers la vidéo.",
        'faq_q3': 'Quels sont les critères d\'éligibilité ?',
        'faq_a3': "Les films doivent utiliser l'intelligence artificielle de manière significative dans leur processus de création (visuel, sonore, scénario, etc.). La durée et le format spécifiques sont détaillés dans le règlement de chaque concours.",
        'faq_q4': "L'inscription est-elle gratuite ?",
        'faq_a4': "L'inscription à la plateforme est gratuite. Certains concours spécifiques peuvent avoir des frais d'inscription, mais la plupart de nos événements sont ouverts à tous sans frais.",
        'faq_q5': 'Comment fonctionne le système de vote ?',
        'faq_a5': "Les films sont soumis au vote d'un jury d'experts ainsi qu'au vote du public pour certains prix. Les critères incluent l'originalité, la qualité technique, et l'utilisation créative de l'IA.",
        'faq_q6': 'Puis-je modifier ma soumission ?',
        'faq_a6': "Une fois soumise, une œuvre ne peut généralement pas être modifiée pendant la période de vote. Si vous avez fait une erreur majeure, veuillez nous contacter directement via le support.",
        'faq_contact_title': 'Vous avez d\'autres questions ?',
        'faq_contact_desc': "Notre équipe est là pour vous aider. N'hésitez pas à nous contacter directement.",
        'faq_contact_btn': 'Nous contacter',
        'faq_discord_btn': 'Support Discord',
        'config_page_title': 'Configuration',
        'config_page_desc': 'Gérez les paramètres du festival',
        'config_playlists_select': 'Sélectionner',
        'config_playlists_count': 'playlists',
        'config_playlists_title_heading': 'Playlists',
        'config_playlists_desc': 'Sélections de films du festival',
        'button_change': 'Changer',
        'button_cancel': 'Annuler',
        'button_delete': 'Supprimer',
        'button_new_playlist': 'Nouvelle playlist',
        'modal_new_playlist_title': 'Nouvelle playlist',
        // Submission Form Keys
        'submission_form_title': 'MarsAI Festival',
        'submission_form_subtitle': 'Générations du Futur',
        'submission_director_section': 'Informations Réalisateur',
        'submission_civility': 'Civilité',
        'submission_civility_mr': 'Monsieur',
        'submission_civility_ms': 'Madame',
        'submission_civility_nb': 'Non-binaire',
        'submission_firstname': 'Prénom *',
        'submission_lastname': 'Nom *',
        'submission_email': 'Email *',
        'submission_mobile': 'Mobile *',
        'submission_birth_date': 'Date de naissance',
        'submission_job_title': 'Fonction / Job Title',
        'submission_address': 'Adresse (Rue, numéro...)',
        'submission_zip_code': 'Code Postal',
        'submission_city': 'Ville',
        'submission_country': 'Pays',
        'submission_newsletter': 'S\'inscrire à la newsletter MarsAI',
        'submission_film_section': 'Votre Film',
        'submission_title_original': 'Titre Original *',
        'submission_title_english': 'Titre Anglais',
        'submission_synopsis_original': 'Synopsis Original',
        'submission_synopsis_english': 'Synopsis Anglais',
        'submission_duration': 'Durée (secondes)',
        'submission_language': 'Langue principale',
        'submission_themes': 'Thèmes / Tags (ex: Science-fiction, Cyberpunk, Drame, IA...)',
        'submission_ai_hybrid': 'Hybride',
        'submission_ai_100percent': '100% IA',
        'submission_ai_tools': 'Outils IA utilisés (ex: Sora, Runway, Midjourney...)',
        'submission_ai_methodology': 'Méthodologie (Prompt engineering, process...)',
        'submission_media_section': 'Fichiers Médias',
        'submission_video_file': 'Vidéo du film (MP4, MOV, AVI, MKV) *',
        'submission_poster_file': 'Affiche / Poster (PNG, JPG, WEBP, JPEG) *',
        'submission_subtitle_file': 'Sous-titres (.srt, .vtt)',
        'submission_gallery_files': 'Galerie d\'images (Plusieurs fichiers possibles)',
        'submission_collaborators_section': 'Collaborateurs',
        'submission_add_collaborator': '+ Ajouter',
        'submission_collab_firstname': 'Prénom',
        'submission_collab_lastname': 'Nom',
        'submission_collab_role': 'Rôle (ex: Monteur, Sound Designer)',
        'submission_collab_email': 'Email',
        'submission_success': 'Succès ! Film reçu et envoyé sur YouTube (ID: {youtube_id})',
        'submission_error': 'Erreur lors de l\'envoi.',
        'submission_uploading': 'Upload Cloud : {progress}%',
        'submission_finalizing': 'Finalisation YouTube...',
        'submission_button': 'Soumettre mon film',
        // Jury Assignment Page Keys
        'jury_assignment_title': 'Assignation des jurés',
        'jury_assignment_desc': 'Gérez les films sélectionnés et les jurés assignés pour cette playlist',
        'jury_assignment_active': 'Playlist active :',
        'jury_assignment_no_selection': 'Aucune sélection',
        'jury_assignment_playlists': 'Playlists disponibles',
        'jury_assignment_loading': 'Chargement des playlists...',
        'jury_assignment_no_playlists': 'Aucune playlist disponible.',
        'jury_assignment_section_films': '1. Sélection des Films',
        'jury_assignment_section_jurors': '2. Assignation des Jurés',
        'jury_assignment_films_available': 'Films Disponibles',
        'jury_assignment_films_selected': 'Films Sélectionnés',
        'jury_assignment_jurors_available': 'Membres Disponibles',
        'jury_assignment_jurors_assigned': 'Jurés Assignés',
        'jury_assignment_all_films_selected': 'Tous les films sont sélectionnés',
        'jury_assignment_no_films': 'Aucun film sélectionné',
        'jury_assignment_all_jurors_assigned': 'Tous les jurés sont assignés',
        'jury_assignment_no_jurors': 'Aucun juré assigné',
        'jury_assignment_duration_unknown': 'Durée inconnue',
        'jury_assignment_page': 'Page',
        // SelectFinaliste Page Keys
        'selectfinaliste_title': 'Selection Finale',
        'selectfinaliste_subtitle': 'Gestion des Finalistes',
        'selectfinaliste_admin': 'Festival Admin',
        'selectfinaliste_total_submitted': 'Total soumis',
        'selectfinaliste_selected': 'Sélectionnés',
        'selectfinaliste_awards_given': 'Prix attribués',
        'selectfinaliste_comments': 'Commentaires',
        'selectfinaliste_selected_films': 'Films Sélectionnés',
        'selectfinaliste_selection_rate': 'de la sélection officielle',
        'selectfinaliste_selected_status': 'Sélectionné',
        'selectfinaliste_pending': 'En attente',
        'selectfinaliste_selected_genres': 'Genres sélectionnés',
        'selectfinaliste_no_films_selected': 'Aucun film sélectionné',
        'selectfinaliste_search_placeholder': 'Rechercher un film ou un réalisateur...',
        'selectfinaliste_all': 'Tous',
        'selectfinaliste_liked': 'Liked',
        'selectfinaliste_to_discuss': 'À discuter',
        'selectfinaliste_director': 'Réalisateur',
        'selectfinaliste_status': 'Statut',
        'selectfinaliste_award': 'Prix',
        'selectfinaliste_actions': 'Actions',
        'selectfinaliste_assign_award': 'Attribuer un prix',
        'selectfinaliste_view_comments': 'Voir les commentaires jury',
        'selectfinaliste_view_likes': 'Voir les likes',
        'selectfinaliste_view_to_discuss': 'Voir les à discuter',
        'selectfinaliste_no_comment': 'Aucun commentaire',
        'selectfinaliste_jury_opinions': 'avis du jury',
        'selectfinaliste_loading': 'Chargement des finalistes...',
        'selectfinaliste_no_films_found': 'Aucun film trouvé',
        'selectfinaliste_previous_page': 'Page precedente',
        'selectfinaliste_next_page': 'Page suivante',
        'selectfinaliste_jury_likes': 'Likes du Jury',
        'selectfinaliste_jury_opinion': 'Avis du Jury',
        'selectfinaliste_no_likes_for_film': 'Aucun like pour ce film',
        'selectfinaliste_no_discusses_for_film': 'Aucun à discuter pour ce film',
        'selectfinaliste_no_comments_for_film': 'Aucun commentaire pour ce film',
        'selectfinaliste_film_removed': 'Film retiré de la sélection',
        'selectfinaliste_film_selected': 'Film sélectionné !',
        'selectfinaliste_error_update': 'Erreur lors de la mise à jour',
        'selectfinaliste_award_assigned': 'Prix attribué : {award}',
        'selectfinaliste_film_selected_no_award': 'Film sélectionné sans prix',
        'selectfinaliste_error_save_award': 'Erreur lors de la sauvegarde du prix',
        // Home Page Modal & Buttons
        'home_video_modal_title': 'Découvrez MarsAI',
        'home_video_part1': 'Partie 1 - Présentation du Site',
        'home_video_part2': 'Partie 2 - Présentation du Formulaire',
        'home_video_intro': 'Bienvenue dans le monde de MarsAI',
        'home_video_description': 'Découvrez notre plateforme révolutionnaire dédiée à la création cinématographique par intelligence artificielle. Dans cette présentation, nous vous guidons à travers les fonctionnalités essentielles et le processus de soumission.',
        'home_video_part1_desc': 'Explorez la présentation complète du site MarsAI, découvrez ses fonctionnalités principales et comment nous révolutionnons l\'industrie cinématographique.',
        'home_video_part2_desc': 'Apprenez comment soumettre vos créations via notre formulaire intuitif et participez à notre compétition mondiale.',
        'home_video_cta_desc': 'Prêt à rejoindre la révolution ? Choisissez ci-dessous comment vous souhaitez contribuer à MarsAI.',
        'home_btn_submit': 'Soumettre un film',
        'home_btn_login_admin': 'Connexion Admin',
        'home_btn_login_jury': 'Connexion Jury',
        'home_cta_get_started': 'Commencer',
        'home_cta_learn_more': 'En savoir plus',
      },
      en: {
        'home': 'HOME',
        'gallery': 'GALLERY',
        'jury': 'JURY',
        'sponsors': 'SPONSORS',
        'submit': 'Submit a film',
        'logout': 'Logout',
        'login': 'Login',
        'hero_title': 'MARS AI FESTIVAL',
        'hero_subtitle': 'Where AI meets cinema',
        'discover': 'Discover',
        'about': 'About',
        'about_title': 'About Mars AI',
        'about_desc': 'An innovative festival celebrating the fusion between artificial intelligence and cinema. Discover how AI transforms filmmaking creativity.',
        'close': 'Close',
        'categories': 'Categories',
        'awards': 'Awards',
        'awards_title': 'Festival Awards',
        'partners': 'Partners',
        'contact': 'Contact',
        'year': '2026',
        'sci_fi': 'SCI-FI',
        'horror': 'HORROR',
        'action': 'ACTION',
        'drama': 'DRAMA',
        'thriller': 'THRILLER',
        'documentary': 'DOCUMENTARY',
        'animation': 'ANIMATION',
        'history': 'HISTORY',
        'footer_description': 'Sci-Fi & AI Festival: films, jury, sponsors, creations and visual exploration. Mobile-first, fast and modern.',
        'footer_navigation': 'NAVIGATION',
        'footer_home': 'Home',
        'footer_gallery': 'Gallery',
        'footer_jury': 'Jury',
        'footer_sponsors': 'Sponsors',
        'footer_submission': 'Submission',
        'footer_infos': 'INFO',
        'footer_location': '📍 Paris / Mars (virtual)',
        'footer_projections': '🎬 Screenings & competition',
        'footer_ai': '🤖 Creative AI',
        'footer_newsletter': 'NEWSLETTER',
        'footer_newsletter_desc': 'Get news, film calls, and festival announcements.',
        'footer_email_placeholder': 'your@email.com',
        'footer_subscribe': 'Subscribe',
        'footer_spam_notice': 'No spam. Unsubscribe with one click.',
        'footer_copyright': 'All rights reserved.',
        'footer_legal': 'Legal Notice',
        'footer_privacy': 'Privacy',
        'login_title': 'LOGIN',
        'login_email': 'Email address',
        'login_password': 'Password',
        'login_button': 'Login',
        'login_google': 'Sign in with Google',
        'login_error': 'Login error',
        'login_forgot': 'Forgot password?',
        'gallery_title': 'Film Gallery',
        'gallery_subtitle': 'Discover films from Mars AI Festival',
        'gallery_search': 'Search for a film...',
        'gallery_loading': 'Loading films...',
        'gallery_error': 'Unable to load films. Please try again later.',
        'gallery_no_results': 'No films match your search.',
        'gallery_by': 'By',
        'gallery_no_synopsis': 'No synopsis',
        'gallery_unknown_duration': 'Unknown duration',
        'gallery_prev': 'Previous',
        'gallery_next': 'Next',
        'gallery_total': 'film(s) total',
        'detail_director': 'Directed by',
        'detail_genres': 'Genres:',
        'detail_ai_class': 'AI Classification:',
        'detail_ai_tools': 'AI Tools Used:',
        'detail_language': 'Language:',
        'detail_duration': 'Duration',
        'detail_minutes': 'minutes',
        'detail_seconds': 'seconds',
        'detail_subtitles': 'Subtitles:',
        'detail_no_synopsis_available': 'No synopsis available',
        'detail_english_synopsis': 'English synopsis:',
        'gallery_images': 'Image Gallery',
        'status': 'Status',
        'detail_pending': 'Pending',
        'detail_approved': 'Approved',
        'detail_rejected': 'Rejected',
        'detail_themes': 'Themes',
        'detail_synopsis': 'Synopsis',
        'detail_english_version': 'View English version →',
        'detail_less': '← View less',
        'detail_methodology': 'AI Methodology',
        'detail_team': 'Production Team',
        'detail_collaborators': 'Collaborators',
        'detail_gallery': 'Gallery',
        'detail_similar': 'Similar Films',
        'detail_loading': 'Loading film...',
        'detail_error': 'Unable to load film details',
        'detail_like': 'Like this film',
        'detail_share': 'Share this film',
        'detail_back': 'Back to gallery',
        'forgot_title': 'Reset-password',
        'forgot_email': 'Email address',
        'forgot_submit': 'Validate →',
        'forgot_back': 'Back to login page',
        'dashboard_user_title': 'User Management',
        'dashboard_user_add': 'Add user',
        'dashboard_user_admin': 'Admin',
        'dashboard_user_jury': 'Jury',
        'dashboard_user_moderator': 'Moderator',
        'dashboard_user_see': 'View',
        'dashboard_user_edit': 'Edit profile',
        'dashboard_user_delete': 'Delete',
        'dashboard_user_fullname': 'Full name:',
        'dashboard_user_email': 'Email:',
        'dashboard_user_role': 'Role:',
        'dashboard_user_cancel': 'Cancel',
        'dashboard_user_save': 'Save',
        'dashboard_user_saving': 'Saving...',
        'dashboard_user_confirm_delete': 'Are you sure you want to delete',
        'dashboard_user_irreversible': '? This action is irreversible.',
        'dashboard_user_success': 'User deleted successfully',
        'dashboard_user_updated': 'User updated successfully!',
        'dashboard_user_invited': 'Invitation sent successfully to',
        'dashboard_user_sending': 'Sending...',
        'dashboard_user_add_invite': 'Add and invite',
        'dashboard_user_column_user': 'User',
        'dashboard_user_column_role': 'Role',
        'dashboard_user_column_actions': 'Actions',
        'dashboard_user_error': 'Error',
        'dashboard_user_error_update': 'Unable to update user',
        'dashboard_user_error_delete': 'Unable to delete user',
        'dashboard_user_error_create': 'Unable to create user',
        'dashboard_title': 'ADMIN DASHBOARD',
        'dashboard_subtitle': 'Overview of activity and submission management',
        'dashboard_admin': 'Administrator',
        'dashboard_function': 'Function',
        'reset_title': 'RESET-PASSWORD',
        'reset_password': 'Password:',
        'reset_confirm': 'Password confirmation:',
        'reset_button': 'RESET',
        'reset_back': 'Back to login',
        'reset_no_token': 'Token missing from URL.',
        'reset_mismatch': 'Passwords do not match.',
        'reset_success': 'Password reset successfully.',
        'notfound_404': '404',
        'notfound_title': 'Page Not Found',
        'notfound_message': 'The page you are looking for has disappeared into an unknown orbit. Return to the station.',
        'notfound_home': 'Back home',
        'jury_loading': 'Loading film...',
        'jury_not_found': 'Film not found',
        'jury_back': 'Back to selection',
        'jury_official': 'Mars AI Festival — Official Selection',
        'jury_fr': '🇫🇷 FR',
        'jury_en': '🇬🇧 EN',
        'jury_evaluate': 'YOUR EVALUATION',
        'jury_evaluate_desc': 'Rate this film and share your professional opinion',
        'jury_like': 'I Like',
        'jury_discuss': 'To Discuss',
        'jury_dislike': 'I Dislike',
        'jury_comment': 'Comment',
        'jury_optional': '(optional)',
        'jury_comment_placeholder': 'Share your impressions, constructive criticism or remarks about this film...',
        'jury_submit': 'Submit my evaluation',
        'jury_submitting': 'Submitting...',
        'jury_success': 'Vote recorded successfully',
        'jury_saved': 'Your evaluation has been saved',
        'jury_edit': 'Edit my vote',
        'jury_error': 'Unable to load film',
        'gestion_films_title': 'Films management',
        'gestion_films_distribution': 'DISTRIBUTION MOVIES',
        'gestion_films_subtitle': 'Manage all submissions, approve or reject submitted films.',
        'gestion_films_admin_label': 'ADMINISTRATOR',
        'gestion_films_email_label': 'DIRECTOR EMAIL',
        'gestion_films_role_label': 'MODERATOR',
        'gestion_films_column_poster': 'Poster',
        'gestion_films_column_title': 'Title',
        'gestion_films_column_director': 'Director',
        'gestion_films_column_status': 'Status',
        'gestion_films_column_date': 'Date',
        'gestion_films_column_actions': 'Actions',
        'gestion_films_search': 'Search for a film…',
        'gestion_films_all': 'All',
        'gestion_films_valid': 'Valid',
        'gestion_films_pending': 'Pending',
        'gestion_films_refused': 'Refused',
        'gestion_films_loading': 'Loading films...',
        'gestion_films_submitted': 'Film submitted',
        'gestion_films_valid_tag': 'VALID',
        'gestion_films_pending_tag': 'PENDING',
        'gestion_films_refused_tag': 'REFUSED',
        'gestion_films_approve': 'Approve',
        'gestion_films_reject': 'Reject',
        'gestion_films_details': 'Details',
        'gestion_films_page': 'Page',
        'gestion_films_all_selected': 'All films are selected',
        'gestion_films_none_selected': 'No films selected',
        'gestion_films_poster': 'Poster',
        'gestion_films_approved_ok': 'Film approved ✓',
        'gestion_films_rejected_ok': 'Film rejected',
        'gestion_films_featured': 'Film featured',
        'gestion_films_unfeatured': 'Removed from featured',
        'gestion_films_status_distribution': 'Status Distribution',
        'gestion_films_status': 'Status',
        'gestion_films_approval_progress': 'Approval Progress',
        'gestion_films_approved': 'Approved',
        'gestion_films_pending_review': 'Pending Review',
        'gestion_films_submission_trend': 'Submission Trend',
        'gestion_films_total_submitted': 'Total Submitted',
        'gestion_films_approval_rate': 'Approval Rate',
        'gestion_films_rejection_rate': 'Rejection Rate',
        'jury_dist_title': 'Jury distribution',
        'jury_dist_subtitle': 'Assign jury members for film evaluation',
        'jury_dist_description': 'Manage jury assignment and their selections for evaluating films.',
        'jury_dist_admin_management': 'Admin Management',
        'jury_dist_admin_label': 'ADMINISTRATOR',
        'jury_dist_email_label': 'EMAIL',
        'jury_dist_role_label': 'ROLE',
        'jury_dist_loading': 'Loading...',
        'jury_dist_vote_distribution': 'Vote Distribution',
        'jury_dist_votes_category': 'Votes',
        'jury_dist_like': 'Like',
        'jury_dist_discuss': 'To discuss',
        'jury_dist_dislike': 'Dislike',
        'jury_dist_global_progress': 'Global Progress',
        'jury_dist_completed': 'Completed',
        'jury_dist_remaining': 'Remaining',
        'jury_dist_progress': 'Progress',
        'jury_dist_active_jurors': 'Active Jurors',
        'competition_anim_title': 'Administrator Space',
        'competition_anim_subtitle': 'Animation Competition',
        'competition_anim_desc': 'Manage selected films and assigned jurors for this category',
        'competition_films': '1. Film Selection',
        'competition_available': 'Available Films',
        'competition_selected': 'Selected Films',
        'competition_all_films_selected': 'All films are selected',
        'competition_no_films': 'No films selected',
        'competition_jury': '2. Jury Assignment',
        'competition_jury_available': 'Available Members',
        'competition_jury_assigned': 'Assigned Jurors',
        'competition_all_jury_assigned': 'All jurors are assigned',
        'competition_no_jury': 'No jurors assigned',
        'jury_management': 'Admin Management',
        'jury_management_title': 'JURY MANAGEMENT',
        'jury_management_desc': 'Jury assignment and their selections for film evaluation.',
        // JuryTab Component Keys
        'jury_form_email_placeholder': 'Email',
        'jury_form_specialty_placeholder': 'Specialty',
        'jury_form_role_jury': 'Jury Member',
        'jury_form_role_lead': 'Jury Leader',
        'jury_form_role_moderator': 'Moderator',
        'jury_add_button': '✅ Add',
        'jury_cancel_button': '✖️ Cancel',
        'jury_unspecified': 'Not specified',
        'jury_progress_label': 'Progress',
        'jury_approved_label': 'Approved',
        'jury_rejected_label': 'Rejected',
        'jury_pending_label': 'To discuss',
        'jury_approval_label': 'Approval',
        'jury_role_leader': '⭐ Leader',
        'jury_role_moderator': '⚖️ Mod',
        'jury_role_member': '📋 Jury',
        'jury_summary_title': '📧 Members Summary',
        'jury_table_name': 'Name',
        'jury_table_role': 'Role',
        'jury_table_progress': 'Progress',
        'jury_table_approved': '✅ Approved',
        'jury_table_rejected': '❌ Rejected',
        'jury_table_approval': 'Approval',
        'jury_role_moderator_full': '⚖️ Moderator',
        'jury_specialty_creative_ai': 'Creative AI',
        'jury_specialty_video_production': 'Video Production',
        'jury_stats_title': 'Global Statistics',
        'jury_jury_members_label': 'Jury Members',
        'jury_films_evaluate_label': 'Films to Evaluate',
        'jury_total_progress_label': 'Total Progress',
        'jury_approved_films_label': 'Approved Films',
        'jury_members_section_title': '👥 Jury Members',
        'jury_add_member_button': '+ Add Member',
        'jury_notes': 'Jury Notes',
        'jury_notes_title': 'Jury Evaluation Notes',
        'jury_notes_subtitle': 'View the evaluations and notes of jury members',
        // Jury Page Keys
        'jury_page_loading': 'Loading jury members...',
        'jury_page_error': 'Unable to load jury members',
        'jury_page_title': 'The Grand Jury',
        'jury_page_presidency': 'Festival Presidency',
        'jury_page_all_filters': 'All',
        'jury_page_filters_cinema': 'Cinema',
        'jury_page_filters_ai': 'AI',
        'jury_page_filters_design': 'Design',
        'jury_page_anonymous': 'Anonymous Member',
        'jury_page_expert': 'Festival Expert',
        'jury_page_details_button': 'Jury Details',
        'jury_page_official_record': 'Official Record',
        'jury_page_jury_id': 'Jury ID',
        'jury_page_accredited': 'Accredited member under number #{id}',
        'jury_page_registered': 'Registered on:',
        'sponsors_title': 'Our Partners',
        'sponsors_intro': 'Mars AI Festival thanks its sponsors for their support in promoting AI-based creativity.',
        // Film Detail Page Keys
        'film_detail_loading': 'Loading film...',
        'film_detail_error': 'Unable to load film details',
        'film_detail_back': 'Back to gallery',
        'film_detail_directed_by': 'Directed by',
        'film_detail_like': 'Like this film',
        'film_detail_share': 'Share this film',
        'film_detail_duration': 'Duration',
        'film_detail_language': 'Language',
        'film_detail_ai': 'AI',
        'film_detail_status': 'Status',
        'film_detail_themes': 'Themes',
        'film_detail_synopsis': 'Synopsis',
        'film_detail_see_less': '← See less',
        'film_detail_see_english': 'See English version →',
        'film_detail_methodology': 'AI Methodology',
        'film_detail_tools_used': 'Tools Used:',
        'film_detail_team': 'Production Team',
        'film_detail_director': 'Director',
        'film_detail_gallery': 'Gallery',
        'film_detail_related': 'Similar Films',
        'film_detail_video_title': 'Film Video',
        'film_detail_status_pending': 'Pending',
        'film_detail_status_approved': 'Approved',
        'film_detail_status_rejected': 'Rejected',
        'film_detail_na': 'N/A',
        'sponsors_gold': 'Gold Sponsors',
        'sponsor_gold_1': 'Gold Sponsor 1',
        'sponsor_gold_1_desc': 'Leader in creative AI solutions',
        'sponsor_gold_2': 'Gold Sponsor 2',
        'sponsor_gold_2_desc': 'Innovators in video technology',
        'sponsors_silver': 'Silver Sponsors',
        'sponsor_silver_1': 'Silver Sponsor 1',
        'sponsor_silver_2': 'Silver Sponsor 2',
        'sponsor_silver_3': 'Silver Sponsor 3',
        'become_sponsor': 'Become a sponsor',
        'become_sponsor_desc': 'Interested in sponsoring Mars AI Festival? Contact us to learn more about partnership opportunities.',
        'contact_us': 'Contact Us',
        // Admin Header Keys
        'admin_dashboard': 'Dashboard',
        'admin_films': 'Films',
        'admin_jury': 'Jury',
        'admin_config': 'Configuration',
        'admin_logout': 'Logout',
        'admin_moderator': 'MODERATOR',
        'admin_role': 'Role',
        // Dashboard Tab Keys
        'dashboard_total_films': 'Total Films',
        'dashboard_total_jury': 'Total Jury',
        'dashboard_approved_label': 'Approved',
        // Films Management Keys
        'films_management': 'Film Management',
        'films_no_films': 'No films at the moment',
        'films_management_title': 'Film Management',
        // Configuration Keys
        'config_title': 'Configuration',
        'config_settings': 'Configuration Settings',
        'config_general': 'General Settings',
        'config_festival_name': 'Festival Name',
        'config_festival_dates': 'Festival Dates',
        'config_save': 'Save',
        'config_saved': 'Configuration saved',
        // Events Tab Keys
        'events_title': 'Events',
        'events_no_events': 'No events at the moment',
        'events_add_event': 'Add Event',
        // Results Tab Keys
        'results_title': 'Results',
        'results_winners': 'Winners',
        'results_categories': 'Categories',
        // Language Toggle
        'lang_fr': '🇫🇷 FR',
        'lang_en': '🇬🇧 EN',
        // Common Admin Actions
        'action_add': 'Add',
        'action_edit': 'Edit',
        'action_delete': 'Delete',
        'action_save': 'Save',
        'action_cancel': 'Cancel',
        'action_back': 'Back',
        'action_confirm': 'Confirm',
        'action_loading': 'Loading...',
        // Modal Keys
        'modal_confirm_delete': 'Are you sure?',
        'modal_confirm_delete_text': 'This action is irreversible.',
        'modal_yes': 'Yes',
        'modal_no': 'No',
        'modal_close': 'Close',
        // Table Headers
        'table_name': 'Name',
        'table_email': 'Email',
        'table_role': 'Role',
        'table_status': 'Status',
        'table_actions': 'Actions',
        'table_date': 'Date',
        // Validation Messages
        'error_required': 'This field is required',
        'error_email': 'Invalid email',
        'error_password_mismatch': 'Passwords do not match',
        'success_saved': 'Saving successful',
        'success_deleted': 'Deletion successful',
        'success_updated': 'Update successful',
        // JuryTab Additional Keys
        'jury_tab_global_stats': 'Global Statistics',
        'jury_tab_members': 'Jury Members',
        'jury_tab_add_member': '+ Add Member',
        'jury_tab_email': 'Email',
        'jury_tab_full_name': 'Full Name',
        'jury_tab_role_option': 'Jury',
        'jury_tab_loading': 'Loading jury members...',
        'jury_tab_add_button': 'Add',
        'jury_tab_cancel_button': 'Cancel',
        'jury_tab_in_progress': 'In progress...',
        'jury_tab_films_to_evaluate': 'Films to Evaluate',
        'jury_tab_total_progress': 'Total Progress',
        'jury_tab_global_decisions': 'Global Decisions',
        'jury_tab_liked': 'Liked',
        'jury_tab_disliked': 'Disliked',
        'jury_tab_to_discuss': 'To Discuss',
        'jury_tab_leader': 'Leader',
        'jury_tab_moderator': 'Moderator',
        'jury_tab_jury': 'Jury',
        'jury_tab_specialty': 'Specialty',
        'jury_tab_progress': 'Progress',
        'jury_tab_approval_rate': 'Approval',
        'jury_tab_no_specialty': '-',
        // Header Keys
        'header_dashboard': 'Dashboard',
        'header_theme': 'Theme',
        'header_mode': 'Mode',
        'dashboard_jury_films_assigned': 'Assigned Films',
        'dashboard_jury_like': 'I Like',
        'dashboard_jury_dislike': 'I Dislike',
        'dashboard_jury_discuss': 'To Discuss',
        'dashboard_jury_my_playlists': 'My Playlists',
        'dashboard_jury_select_playlist': 'Select a playlist to view videos',
        'dashboard_jury_loading': 'Loading playlists...',
        'dashboard_jury_error_loading': 'Unable to load data',
        'dashboard_jury_unknown_director': 'Unknown Director',
        'admin_space': 'Administrator Space',
        'admin_dashboard_title': 'Admin dashboard',
        'admin_dashboard_subtitle': 'Overview of platform activity',
        'dashboard_submissions': 'Submissions',
        'dashboard_statistics_approved': 'Approved',
        'dashboard_statistics_rejected': 'Rejected',
        'dashboard_statistics_pending': 'Pending',
        'dashboard_evolution_title': 'Submission Evolution',
        'dashboard_evolution_subtitle': 'Statistics over the last 8 weeks',
        'dashboard_categories_title': 'Category Distribution',
        'dashboard_users_management': 'User Management',
        'dashboard_users_button': 'View Users',
        'dashboard_finalists_selection': 'Finalist Selection',
        'dashboard_finalists_button': 'Manage Finalists',
        'films_no_results': 'No films found',
        'films_no_results_search': 'for',
        'badge_valid': 'VALID',
        'badge_pending': 'PENDING',
        'badge_rejected': 'REJECTED',
        'button_approve': 'Approve',
        'button_reject': 'Reject',
        'button_details': 'Details',
        'films_featured': 'Film featured',
        'films_unfeatured': 'Removed from featured',
        'notifications_error_loading': 'Error loading films',
        'error_moderation': 'Error moderating film',
        'toast_approved': 'Film approved ✓',
        'toast_rejected': 'Film rejected',
        'config_home_title': 'Configuration Home',
        'config_home_desc': 'Manage visible sections on the public home page',
        'config_playlists_title': 'Festival Film Selections',
        'config_assign_title': 'Assign Films & Jury',
        'config_assign_desc': 'Associate films and jury members with your playlists',
        'config_film_singular': 'film',
        'config_film_plural': 'films',
        'config_jury_singular': 'member',
        'config_jury_plural': 'jury members',
        'notation_loading': 'Loading film...',
        'notation_back': 'Back',
        'notation_back_selection': 'Back to selection',
        'notation_your_evaluation': 'YOUR EVALUATION',
        'notation_comment': 'Comment',
        'notation_submit': 'Submit my evaluation',
        'notation_saved_message': 'Your evaluation has been saved and cannot be modified',
        'notation_error_submit': 'Error submitting vote. Please try again.',
        'notation_director': 'Director',
        'notation_duration': 'Duration',
        'notation_contact': 'Email',
        'notation_location': 'Location',
        'notation_production_year': 'Production Year',
        'notation_themes': 'Themes',
        'notation_synopsis': 'Synopsis',
        'notation_watch_film': 'Watch the film',
        'notation_official_selection': 'Mars AI Festival — Official Selection',
        'notation_evaluation_subtitle': 'Rate this film and share your professional opinion',
        'notation_comment_placeholder': 'Share your impressions, constructive criticism or remarks about this film...',
        'notation_vote_success': 'Vote successfully recorded',
        'notation_vote_like': 'Like',
        'notation_vote_discuss': 'To Discuss',
        'notation_vote_dislike': 'Dislike',
        // FAQ Page Keys (English)
        'faq_title': 'Frequently Asked Questions',
        'faq_subtitle': 'Find answers to the most common questions about the festival, submissions and how the Mars AI platform works.',
        'faq_q1': 'What is Mars AI?',
        'faq_a1': 'Mars AI is a platform dedicated to filmmaking assisted by artificial intelligence. We organize festivals, competitions and provide a showcase for creators using AI in their work.',
        'faq_q2': 'How do I submit a film?',
        'faq_a2': 'To submit a film, you must create an account, log in, then click on \'Submission\' in the menu. Fill in the form with the details of your work and the link to the video.',
        'faq_q3': 'What are the eligibility criteria?',
        'faq_a3': 'Films must use artificial intelligence in a meaningful way in their creation process (visual, sound, screenplay, etc.). The specific duration and format are detailed in the regulations of each competition.',
        'faq_q4': 'Is registration free?',
        'faq_a4': 'Registration on the platform is free. Some specific competitions may have registration fees, but most of our events are open to all at no cost.',
        'faq_q5': 'How does the voting system work?',
        'faq_a5': 'Films are submitted to voting by a panel of experts as well as public voting for some awards. Criteria include originality, technical quality, and creative use of AI.',
        'faq_q6': 'Can I modify my submission?',
        'faq_a6': 'Once submitted, a work generally cannot be modified during the voting period. If you made a major error, please contact us directly via support.',
        'faq_contact_title': 'Have more questions?',
        'faq_contact_desc': 'Our team is here to help you. Feel free to contact us directly.',
        'faq_contact_btn': 'Contact us',
        'faq_discord_btn': 'Discord Support',
        'config_page_title': 'Configuration',
        'config_page_desc': 'Manage festival settings',
        'config_playlists_select': 'Select',
        'config_playlists_count': 'playlists',
        'config_playlists_title_heading': 'Playlists',
        'config_playlists_desc': 'Festival film selections',
        'button_change': 'Change',
        'button_cancel': 'Cancel',
        'button_delete': 'Delete',
        'button_new_playlist': 'New playlist',
        'modal_new_playlist_title': 'New playlist',
        // Submission Form Keys
        'submission_form_title': 'MarsAI Festival',
        'submission_form_subtitle': 'Future Generations',
        'submission_director_section': 'Director Information',
        'submission_civility': 'Civility',
        'submission_civility_mr': 'Mr',
        'submission_civility_ms': 'Ms',
        'submission_civility_nb': 'Non-binary',
        'submission_firstname': 'First Name *',
        'submission_lastname': 'Last Name *',
        'submission_email': 'Email *',
        'submission_mobile': 'Mobile *',
        'submission_birth_date': 'Date of Birth',
        'submission_job_title': 'Job Title / Function',
        'submission_address': 'Address (Street, number...)',
        'submission_zip_code': 'Zip Code',
        'submission_city': 'City',
        'submission_country': 'Country',
        'submission_newsletter': 'Subscribe to MarsAI newsletter',
        'submission_film_section': 'Your Film',
        'submission_title_original': 'Original Title *',
        'submission_title_english': 'English Title',
        'submission_synopsis_original': 'Original Synopsis',
        'submission_synopsis_english': 'English Synopsis',
        'submission_duration': 'Duration (seconds)',
        'submission_language': 'Main Language',
        'submission_themes': 'Themes / Tags (ex: Science-fiction, Cyberpunk, Drama, AI...)',
        'submission_ai_hybrid': 'Hybrid',
        'submission_ai_100percent': '100% AI',
        'submission_ai_tools': 'AI Tools Used (ex: Sora, Runway, Midjourney...)',
        'submission_ai_methodology': 'Methodology (Prompt engineering, process...)',
        'submission_media_section': 'Media Files',
        'submission_video_file': 'Film Video (MP4, MOV, AVI, MKV) *',
        'submission_poster_file': 'Poster / Cover (PNG, JPG, WEBP, JPEG) *',
        'submission_subtitle_file': 'Subtitles (.srt, .vtt)',
        'submission_gallery_files': 'Image Gallery (Multiple files possible)',
        'submission_collaborators_section': 'Collaborators',
        'submission_add_collaborator': '+ Add',
        'submission_collab_firstname': 'First Name',
        'submission_collab_lastname': 'Last Name',
        'submission_collab_role': 'Role (ex: Editor, Sound Designer)',
        'submission_collab_email': 'Email',
        'submission_success': 'Success! Film received and sent to YouTube (ID: {youtube_id})',
        'submission_error': 'Error sending submission.',
        'submission_uploading': 'Upload Cloud: {progress}%',
        'submission_finalizing': 'Finalizing YouTube...',
        'submission_button': 'Submit my film',
        // Jury Assignment Page Keys
        'jury_assignment_title': 'Jury assignment',
        'jury_assignment_desc': 'Manage selected films and assigned jurors for this playlist',
        'jury_assignment_active': 'Active Playlist:',
        'jury_assignment_no_selection': 'No selection',
        'jury_assignment_playlists': 'Available Playlists',
        'jury_assignment_loading': 'Loading playlists...',
        'jury_assignment_no_playlists': 'No playlists available.',
        'jury_assignment_section_films': '1. Film Selection',
        'jury_assignment_section_jurors': '2. Jury Assignment',
        'jury_assignment_films_available': 'Available Films',
        'jury_assignment_films_selected': 'Selected Films',
        'jury_assignment_jurors_available': 'Available Members',
        'jury_assignment_jurors_assigned': 'Assigned Jurors',
        'jury_assignment_all_films_selected': 'All films are selected',
        'jury_assignment_no_films': 'No film selected',
        'jury_assignment_all_jurors_assigned': 'All jurors are assigned',
        'jury_assignment_no_jurors': 'No juror assigned',
        'jury_assignment_duration_unknown': 'Unknown duration',
        'jury_assignment_page': 'Page',
        // Home Page Modal & Buttons (English)
        'home_video_modal_title': 'Discover MarsAI',
        'home_video_part1': 'Part 1 - Site Presentation',
        'home_video_part2': 'Part 2 - Form Presentation',
        'home_video_intro': 'Welcome to the world of MarsAI',
        'home_video_description': 'Discover our revolutionary platform dedicated to filmmaking through artificial intelligence. In this presentation, we guide you through the essential features and submission process.',
        'home_video_part1_desc': 'Explore the complete presentation of the MarsAI site, discover its main features and how we are revolutionizing the film industry.',
        'home_video_part2_desc': 'Learn how to submit your creations through our intuitive form and participate in our global competition.',
        'home_video_cta_desc': 'Ready to join the revolution? Choose below how you want to contribute to MarsAI.',
        'home_btn_submit': 'Submit a Film',
        'home_btn_login_admin': 'Admin Login',
        'home_btn_login_jury': 'Jury Login',
        'home_cta_get_started': 'Get Started',
        'home_cta_learn_more': 'Learn More',
        // SelectFinaliste Page Keys (English)
        'selectfinaliste_title': 'Final Selection',
        'selectfinaliste_subtitle': 'Finalist Management',
        'selectfinaliste_admin': 'Festival Admin',
        'selectfinaliste_total_submitted': 'Total Submitted',
        'selectfinaliste_selected': 'Selected',
        'selectfinaliste_awards_given': 'Awards Given',
        'selectfinaliste_comments': 'Comments',
        'selectfinaliste_selected_films': 'Selected Films',
        'selectfinaliste_selection_rate': 'of official selection',
        'selectfinaliste_selected_status': 'Selected',
        'selectfinaliste_pending': 'Pending',
        'selectfinaliste_selected_genres': 'Selected Genres',
        'selectfinaliste_no_films_selected': 'No films selected',
        'selectfinaliste_search_placeholder': 'Search for a film or director...',
        'selectfinaliste_all': 'All',
        'selectfinaliste_liked': 'Liked',
        'selectfinaliste_to_discuss': 'To Discuss',
        'selectfinaliste_director': 'Director',
        'selectfinaliste_status': 'Status',
        'selectfinaliste_award': 'Award',
        'selectfinaliste_actions': 'Actions',
        'selectfinaliste_assign_award': 'Assign an award',
        'selectfinaliste_view_comments': 'View jury comments',
        'selectfinaliste_view_likes': 'View likes',
        'selectfinaliste_view_to_discuss': 'View to discuss',
        'selectfinaliste_no_comment': 'No comment',
        'selectfinaliste_jury_opinions': 'jury opinions',
        'selectfinaliste_loading': 'Loading finalists...',
        'selectfinaliste_no_films_found': 'No films found',
        'selectfinaliste_previous_page': 'Previous page',
        'selectfinaliste_next_page': 'Next page',
        'selectfinaliste_jury_likes': 'Jury Likes',
        'selectfinaliste_jury_opinion': 'Jury Opinion',
        'selectfinaliste_no_likes_for_film': 'No likes for this film',
        'selectfinaliste_no_discusses_for_film': 'No discussions for this film',
        'selectfinaliste_no_comments_for_film': 'No comments for this film',
        'selectfinaliste_film_removed': 'Film removed from selection',
        'selectfinaliste_film_selected': 'Film selected!',
        'selectfinaliste_error_update': 'Error updating selection',
        'selectfinaliste_award_assigned': 'Award assigned: {award}',
        'selectfinaliste_film_selected_no_award': 'Film selected without award',
        'selectfinaliste_error_save_award': 'Error saving award',
      }
    };

    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
