import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('language') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => prev === 'fr' ? 'en' : 'fr');
  };

  const t = (key) => {
    const translations = {
      fr: {
        'home': 'ACCUEIL',
        'gallery': 'GALERIE',
        'jury': 'JURY',
        'sponsors': 'SPONSORS',
        'submit': 'Soumettre un film',
        'logout': 'Déconnexion',
        'login': 'Connexion',
        'hero_title': 'FESTIVAL MARS AI',
        'hero_subtitle': 'Où l\'IA rencontre le cinéma',
        'discover': 'Découvrir',
        'about': 'À Propos',
        'about_title': 'À propos de Mars AI',
        'about_desc': 'Un festival innovant célébrant la fusion entre l\'intelligence artificielle et le cinéma. Découvrez comment l\'IA transforme la créativité filmique.',
        'close': 'Fermer',
        'categories': 'Catégories',
        'awards': 'Récompenses',
        'awards_title': 'Les Récompenses du Festival',
        'partners': 'Partenaires',
        'contact': 'Contact',
        'year': '2026',
        'sci_fi': 'SCI-FI',
        'horror': 'HORREUR',
        'action': 'ACTION',
        'drama': 'DRAME',
        'thriller': 'THRILLER',
        'documentary': 'DOCUMENTAIRE',
        'animation': 'ANIMATION',
        'history': 'HISTOIRE',
        'footer_description': 'Festival Sci-Fi & IA : films, jury, sponsors, créations et exploration visuelle. Mobile-first, rapide et moderne.',
        'footer_navigation': 'NAVIGATION',
        'footer_home': 'Accueil',
        'footer_gallery': 'Galerie',
        'footer_jury': 'Jury',
        'footer_sponsors': 'Sponsors',
        'footer_submission': 'Soumission',
        'footer_infos': 'INFOS',
        'footer_location': '📍 Paris / Mars (virtuel)',
        'footer_projections': '🎬 Projections & concours',
        'footer_ai': '🤖 IA créative',
        'footer_newsletter': 'NEWSLETTER',
        'footer_newsletter_desc': 'Reçois les actus, appels à films, et annonces du festival.',
        'footer_email_placeholder': 'ton@email.com',
        'footer_subscribe': 'S\'inscrire',
        'footer_spam_notice': 'Zéro spam. Désinscription en 1 clic.',
        'footer_copyright': 'Tous droits réservés.',
        'footer_legal': 'Mentions légales',
        'footer_privacy': 'Confidentialité',
        'login_title': 'CONNEXION',
        'login_email': 'Adresse mail',
        'login_password': 'Mot de passe',
        'login_button': 'Connexion',
        'login_google': 'Se connecter avec Google',
        'login_error': 'Erreur de connexion',
        'login_forgot': 'Mot de passe oublié ?',
        'gallery_title': 'Galerie des Films',
        'gallery_subtitle': 'Découvrez les films du Festival Mars AI',
        'gallery_search': 'Rechercher un film...',
        'gallery_loading': 'Chargement des films...',
        'gallery_error': 'Impossible de charger les films. Veuillez réessayer plus tard.',
        'gallery_no_results': 'Aucun film ne correspond à votre recherche.',
        'gallery_by': 'Par',
        'gallery_no_synopsis': 'Pas de synopsis',
        'gallery_unknown_duration': 'Durée inconnue',
        'gallery_prev': 'Précédent',
        'gallery_next': 'Suivant',
        'gallery_total': 'film(s) au total',
        'detail_director': 'Réalisé par',
        'detail_genres': 'Genres :',
        'detail_ai_class': 'Classification IA :',
        'detail_ai_tools': 'Outils IA utilisés :',
        'detail_language': 'Langue :',
        'detail_duration': 'Durée',
        'detail_status': 'Statut',
        'detail_pending': 'En attente',
        'detail_approved': 'Approuvé',
        'detail_rejected': 'Rejeté',
        'detail_themes': 'Thèmes',
        'detail_synopsis': 'Synopsis',
        'detail_english_version': 'Voir la version anglaise →',
        'detail_less': '← Voir moins',
        'detail_methodology': 'Méthodologie IA',
        'detail_team': 'Équipe de production',
        'detail_collaborators': 'Collaborateurs',
        'detail_gallery': 'Galerie',
        'detail_similar': 'Films similaires',
        'detail_loading': 'Chargement du film...',
        'detail_error': 'Impossible de charger les détails du film',
        'detail_like': 'Aimer ce film',
        'detail_share': 'Partager ce film',
        'detail_back': 'Retour à la galerie',
        'forgot_title': 'Reset-password',
        'forgot_email': 'Adresse mail',
        'forgot_submit': 'Valider →',
        'forgot_back': 'Retour à la page de connexion',
        'dashboard_user_title': 'Gestion des utilisateurs',
        'dashboard_user_add': 'Ajouter un utilisateur',
        'dashboard_user_admin': 'Admin',
        'dashboard_user_jury': 'Jury',
        'dashboard_user_moderator': 'Modérateur',
        'dashboard_user_see': 'Voir',
        'dashboard_user_edit': 'Modifier profil',
        'dashboard_user_delete': 'Supprimer',
        'dashboard_user_fullname': 'Nom complet :',
        'dashboard_user_email': 'Email :',
        'dashboard_user_role': 'Rôle :',
        'dashboard_user_cancel': 'Annuler',
        'dashboard_user_save': 'Enregistrer',
        'dashboard_user_saving': 'Enregistrement...',
        'dashboard_user_confirm_delete': 'Êtes-vous sûr de vouloir supprimer',
        'dashboard_user_irreversible': '? Cette action est irréversible.',
        'dashboard_user_success': 'Utilisateur supprimé avec succès',
        'dashboard_user_updated': 'Utilisateur mis à jour avec succès !',
        'dashboard_user_invited': 'Invitation envoyée avec succès à',
        'dashboard_title': 'TABLEAU ADMIN',
        'dashboard_subtitle': 'Vue générale de l\'activité et gestion des soumissions',
        'dashboard_admin': 'Administrateur',
        'dashboard_function': 'Fonction',
        'dashboard_submissions': 'Soumissions',
        'dashboard_approved': 'Approuvés',
        'dashboard_rejected': 'Rejetés',
        'dashboard_pending': 'En attente',
        'dashboard_evolution': 'Évolution des soumissions',
        'dashboard_data': 'Données simulées par mois',
        'dashboard_categories': 'Répartition des catégories',
        'dashboard_short': 'Court-métrage',
        'dashboard_fiction': 'Fiction',
        'dashboard_users_manage': 'Gestion des utilisateurs',
        'dashboard_users_see': 'Voir les utilisateurs',
        'dashboard_films_manage': 'Gestion des films',
        'dashboard_films_see': 'Voir les films',
        'submission_title': 'MarsAI Festival',
        'submission_generation': 'Générations du Futur',
        'submission_director_info': 'Informations Réalisateur',
        'submission_civility': 'Civilité',
        'submission_mr': 'Monsieur',
        'submission_mrs': 'Madame',
        'submission_other': 'Non-binaire',
        'submission_firstname': 'Prénom *',
        'submission_lastname': 'Nom *',
        'submission_email': 'Email *',
        'submission_phone': 'Mobile *',
        'submission_job': 'Fonction / Job Title',
        'submission_zip': 'Code Postal',
        'submission_city': 'Ville',
        'submission_country': 'Pays',
        'submission_address': 'Adresse (Rue, numéro...)',
        'submission_newsletter': 'S\'inscrire à la newsletter MarsAI',
        'submission_film': 'Votre Film',
        'submission_title_original': 'Titre Original *',
        'submission_title_english': 'Titre Anglais',
        'submission_synopsis_original': 'Synopsis Original',
        'submission_synopsis_english': 'Synopsis Anglais',
        'submission_duration': 'Durée (secondes)',
        'submission_language': 'Langue principale',
        'submission_themes': 'Thèmes / Tags (ex: Science-fiction, Cyberpunk, Drame, IA...)',
        'submission_hybrid': 'Hybride',
        'submission_ai_only': '100% IA',
        'submission_ai_tools': 'Outils IA utilisés (ex: Sora, Runway, Midjourney...)',
        'submission_methodology': 'Méthodologie (Prompt engineering, process...)',
        'submission_media': 'Fichiers Médias',
        'submission_video': 'Vidéo du film (MP4, MOV, AVI, MKV) *',
        'submission_poster': 'Affiche / Poster (PNG, JPG, WEBP, JPEG) *',
        'submission_subtitles': 'Sous-titres (.srt, .vtt)',
        'submission_gallery': 'Galerie d\'images (Plusieurs fichiers possibles)',
        'submission_collaborators': 'Collaborateurs',
        'submission_add': '+ Ajouter',
        'submission_submit': 'Soumettre mon film',
        'submission_upload': 'Upload Cloud :',
        'submission_youtube': 'Finalisation YouTube...',
        'submission_success': 'Succès ! Film reçu et envoyé sur YouTube (ID:',
        'submission_error': 'Erreur lors de l\'envoi.',
        'reset_title': 'RESET-PASSWORD',
        'reset_password': 'Mot de passe :',
        'reset_confirm': 'Confirmation du mot de passe :',
        'reset_button': 'RÉINITIALISER',
        'reset_back': 'Retour à la connexion',
        'reset_no_token': 'Token manquant dans l\'URL.',
        'reset_mismatch': 'Les mots de passe ne correspondent pas.',
        'reset_success': 'Mot de passe réinitialisé avec succès.',
        'notfound_404': '404',
        'notfound_title': 'Page introuvable',
        'notfound_message': 'La page que vous cherchez a disparu dans une orbite inconnue. Revenez a la station.',
        'notfound_home': 'Retour accueil',
        'jury_loading': 'Chargement du film...',
        'jury_not_found': 'Film introuvable',
        'jury_back': 'Retour à la sélection',
        'jury_official': 'Festival Mars AI — Sélection officielle',
        'jury_fr': '🇫🇷 FR',
        'jury_en': '🇬🇧 EN',
        'jury_evaluate': 'VOTRE ÉVALUATION',
        'jury_evaluate_desc': 'Notez ce film et partagez votre avis professionnel',
        'jury_like': 'J\'aime',
        'jury_discuss': 'À discuter',
        'jury_dislike': 'J\'aime pas',
        'jury_comment': 'Commentaire',
        'jury_optional': '(optionnel)',
        'jury_comment_placeholder': 'Partagez vos impressions, critiques constructives ou remarques sur ce film...',
        'jury_submit': 'Soumettre mon évaluation',
        'jury_submitting': 'Soumission en cours...',
        'jury_success': 'Vote enregistré avec succès',
        'jury_saved': 'Votre évaluation a été sauvegardée',
        'jury_edit': 'Modifier mon vote',
        'jury_error': 'Impossible de charger le film',
        'gestion_films_title': 'GESTION FILMS',
        'gestion_films_distribution': 'DISTRIBUTION MOVIES',
        'gestion_films_subtitle': 'Gérez l\'intégralité des soumissions, approuvez ou rejetez les films soumis.',
        'gestion_films_admin_label': 'ADMINISTRATEUR',
        'gestion_films_email_label': 'EMAIL DU RÉALISATEUR',
        'gestion_films_role_label': 'MODÉRATEUR',
        'gestion_films_column_poster': 'Affiche',
        'gestion_films_column_title': 'Titre',
        'gestion_films_column_director': 'Réalisateur',
        'gestion_films_column_status': 'Statut',
        'gestion_films_column_date': 'Date',
        'gestion_films_column_actions': 'Actions',
        'gestion_films_search': 'Rechercher un film…',
        'gestion_films_all': 'Tous',
        'gestion_films_valid': 'Validé',
        'gestion_films_pending': 'En attente',
        'gestion_films_refused': 'Refusé',
        'gestion_films_loading': 'Chargement des films...',
        'gestion_films_submitted': 'Film soumis',
        'gestion_films_valid_tag': 'VALIDÉ',
        'gestion_films_pending_tag': 'EN ATTENTE',
        'gestion_films_refused_tag': 'REFUSÉ',
        'gestion_films_approve': 'Approuver',
        'gestion_films_reject': 'Rejeter',
        'gestion_films_details': 'Détails',
        'gestion_films_page': 'Page',
        'gestion_films_all_selected': 'Tous les films sont sélectionnés',
        'gestion_films_none_selected': 'Aucun film sélectionné',
        'gestion_films_poster': 'Affiche',
        'gestion_films_approved_ok': 'Film approuvé ✓',
        'gestion_films_rejected_ok': 'Film rejeté',
        'gestion_films_featured': 'Film mis en avant',
        'gestion_films_unfeatured': 'Retiré de la mise en avant',
        'jury_dist_title': 'DISTRIBUTION JURY',
        'jury_dist_subtitle': 'Assignez les membres du jury pour l\'évaluation des films',
        'jury_dist_description': 'Gérez l\'assignation des jurés et leurs sélections pour évaluer les films.',
        'jury_dist_admin_management': 'Gestion Admin',
        'jury_dist_admin_label': 'ADMINISTRATEUR',
        'jury_dist_email_label': 'EMAIL',
        'jury_dist_role_label': 'RÔLE',
        'jury_dist_loading': 'Chargement...',
        'competition_anim_title': 'Espace Administrateur',
        'competition_anim_subtitle': 'Compétition Animation',
        'competition_anim_desc': 'Gérez les films sélectionnés et les jurés assignés pour cette catégorie',
        'competition_films': '1. Sélection des Films',
        'competition_available': 'Films Disponibles',
        'competition_selected': 'Films Sélectionnés',
        'competition_all_films_selected': 'Tous les films sont sélectionnés',
        'competition_no_films': 'Aucun film sélectionné',
        'competition_jury': '2. Assignation des Jurés',
        'competition_jury_available': 'Membres Disponibles',
        'competition_jury_assigned': 'Jurés Assignés',
        'competition_all_jury_assigned': 'Tous les jurés sont assignés',
        'competition_no_jury': 'Aucun juré assigné',
        'jury_management': 'Gestion Admin',
        'jury_management_title': 'GESTION JURYS',
        'jury_management_desc': 'Assignation des jurés et leurs sélections pour l\'évaluation des films.',
        // JuryTab Component Keys FR
        'jury_form_email_placeholder': 'Email',
        'jury_form_specialty_placeholder': 'Spécialité',
        'jury_form_role_jury': 'Membre du Jury',
        'jury_form_role_lead': 'Leader du Jury',
        'jury_form_role_moderator': 'Modérateur',
        'jury_add_button': '✅ Ajouter',
        'jury_cancel_button': '✖️ Annuler',
        'jury_unspecified': 'Non spécifié',
        'jury_progress_label': 'Progression',
        'jury_approved_label': 'Approuvés',
        'jury_rejected_label': 'Rejetés',
        'jury_pending_label': 'À discuter',
        'jury_approval_label': 'Approbation',
        'jury_role_leader': '⭐ Leader',
        'jury_role_moderator': '⚖️ Mod',
        'jury_role_member': '📋 Jury',
        'jury_summary_title': '📧 Résumé des Membres',
        'jury_table_name': 'Nom',
        'jury_table_role': 'Rôle',
        'jury_table_progress': 'Progression',
        'jury_table_approved': '✅ Approuvés',
        'jury_table_rejected': '❌ Rejetés',
        'jury_table_approval': 'Approbation',
        'jury_role_moderator_full': '⚖️ Modérateur',
        'jury_specialty_creative_ai': 'IA Créative',
        'jury_specialty_video_production': 'Production Vidéo',
        'jury_stats_title': 'Statistiques Globales',
        'jury_jury_members_label': 'Membres du jury',
        'jury_films_evaluate_label': 'Films à évaluer',
        'jury_total_progress_label': 'Progression totale',
        'jury_approved_films_label': 'Films approuvés',
        'jury_members_section_title': '👥 Membres du Jury',
        'jury_add_member_button': '+ Ajouter un membre',
        'jury_notes': 'Notas du Jury',
        'jury_notes_title': 'Notes d\'Évaluation du Jury',
        'jury_notes_subtitle': 'Consultez les évaluations et notes des membres du jury',
        // Sponsors Page Keys
        'sponsors_title': 'Nos partenaires',
        'sponsors_intro': 'Le Mars AI Festival remercie ses sponsors pour leur soutien dans la promotion de la créativité basée sur l\'intelligence artificielle.',
        'sponsors_gold': 'Sponsors Or',
        'sponsor_gold_1': 'Sponsor Or 1',
        'sponsor_gold_1_desc': 'Leader en solutions IA créatives',
        'sponsor_gold_2': 'Sponsor Or 2',
        'sponsor_gold_2_desc': 'Innovateurs dans la technologie vidéo',
        'sponsors_silver': 'Sponsors Argent',
        'sponsor_silver_1': 'Sponsor Argent 1',
        'sponsor_silver_2': 'Sponsor Argent 2',
        'sponsor_silver_3': 'Sponsor Argent 3',
        'become_sponsor': 'Devenir sponsor',
        'become_sponsor_desc': 'Intéressé par le sponsoring du Mars AI Festival ? Contactez-nous pour en savoir plus sur les opportunités de partenariat.',
        'contact_us': 'Nous contacter',
      },
      en: {
        'home': 'HOME',
        'gallery': 'GALLERY',
        'jury': 'JURY',
        'sponsors': 'SPONSORS',
        'submit': 'Submit a film',
        'logout': 'Logout',
        'login': 'Login',
        'hero_title': 'MARS AI FESTIVAL',
        'hero_subtitle': 'Where AI meets cinema',
        'discover': 'Discover',
        'about': 'About',
        'about_title': 'About Mars AI',
        'about_desc': 'An innovative festival celebrating the fusion between artificial intelligence and cinema. Discover how AI transforms filmmaking creativity.',
        'close': 'Close',
        'categories': 'Categories',
        'awards': 'Awards',
        'awards_title': 'Festival Awards',
        'partners': 'Partners',
        'contact': 'Contact',
        'year': '2026',
        'sci_fi': 'SCI-FI',
        'horror': 'HORROR',
        'action': 'ACTION',
        'drama': 'DRAMA',
        'thriller': 'THRILLER',
        'documentary': 'DOCUMENTARY',
        'animation': 'ANIMATION',
        'history': 'HISTORY',
        'footer_description': 'Sci-Fi & AI Festival: films, jury, sponsors, creations and visual exploration. Mobile-first, fast and modern.',
        'footer_navigation': 'NAVIGATION',
        'footer_home': 'Home',
        'footer_gallery': 'Gallery',
        'footer_jury': 'Jury',
        'footer_sponsors': 'Sponsors',
        'footer_submission': 'Submission',
        'footer_infos': 'INFO',
        'footer_location': '📍 Paris / Mars (virtual)',
        'footer_projections': '🎬 Screenings & competition',
        'footer_ai': '🤖 Creative AI',
        'footer_newsletter': 'NEWSLETTER',
        'footer_newsletter_desc': 'Get news, film calls, and festival announcements.',
        'footer_email_placeholder': 'your@email.com',
        'footer_subscribe': 'Subscribe',
        'footer_spam_notice': 'No spam. Unsubscribe with one click.',
        'footer_copyright': 'All rights reserved.',
        'footer_legal': 'Legal Notice',
        'footer_privacy': 'Privacy',
        'login_title': 'LOGIN',
        'login_email': 'Email address',
        'login_password': 'Password',
        'login_button': 'Login',
        'login_google': 'Sign in with Google',
        'login_error': 'Login error',
        'login_forgot': 'Forgot password?',
        'gallery_title': 'Film Gallery',
        'gallery_subtitle': 'Discover films from Mars AI Festival',
        'gallery_search': 'Search for a film...',
        'gallery_loading': 'Loading films...',
        'gallery_error': 'Unable to load films. Please try again later.',
        'gallery_no_results': 'No films match your search.',
        'gallery_by': 'By',
        'gallery_no_synopsis': 'No synopsis',
        'gallery_unknown_duration': 'Unknown duration',
        'gallery_prev': 'Previous',
        'gallery_next': 'Next',
        'gallery_total': 'film(s) total',
        'detail_director': 'Directed by',
        'detail_genres': 'Genres:',
        'detail_ai_class': 'AI Classification:',
        'detail_ai_tools': 'AI Tools Used:',
        'detail_language': 'Language:',
        'detail_duration': 'Duration',
        'detail_status': 'Status',
        'detail_pending': 'Pending',
        'detail_approved': 'Approved',
        'detail_rejected': 'Rejected',
        'detail_themes': 'Themes',
        'detail_synopsis': 'Synopsis',
        'detail_english_version': 'View English version →',
        'detail_less': '← View less',
        'detail_methodology': 'AI Methodology',
        'detail_team': 'Production Team',
        'detail_collaborators': 'Collaborators',
        'detail_gallery': 'Gallery',
        'detail_similar': 'Similar Films',
        'detail_loading': 'Loading film...',
        'detail_error': 'Unable to load film details',
        'detail_like': 'Like this film',
        'detail_share': 'Share this film',
        'detail_back': 'Back to gallery',
        'forgot_title': 'Reset-password',
        'forgot_email': 'Email address',
        'forgot_submit': 'Validate →',
        'forgot_back': 'Back to login page',
        'dashboard_user_title': 'User Management',
        'dashboard_user_add': 'Add user',
        'dashboard_user_admin': 'Admin',
        'dashboard_user_jury': 'Jury',
        'dashboard_user_moderator': 'Moderator',
        'dashboard_user_see': 'View',
        'dashboard_user_edit': 'Edit profile',
        'dashboard_user_delete': 'Delete',
        'dashboard_user_fullname': 'Full name:',
        'dashboard_user_email': 'Email:',
        'dashboard_user_role': 'Role:',
        'dashboard_user_cancel': 'Cancel',
        'dashboard_user_save': 'Save',
        'dashboard_user_saving': 'Saving...',
        'dashboard_user_confirm_delete': 'Are you sure you want to delete',
        'dashboard_user_irreversible': '? This action is irreversible.',
        'dashboard_user_success': 'User deleted successfully',
        'dashboard_user_updated': 'User updated successfully!',
        'dashboard_user_invited': 'Invitation sent successfully to',
        'dashboard_title': 'ADMIN DASHBOARD',
        'dashboard_subtitle': 'Overview of activity and submission management',
        'dashboard_admin': 'Administrator',
        'dashboard_function': 'Function',
        'dashboard_submissions': 'Submissions',
        'dashboard_approved': 'Approved',
        'dashboard_rejected': 'Rejected',
        'dashboard_pending': 'Pending',
        'dashboard_evolution': 'Submission Evolution',
        'dashboard_data': 'Simulated data per month',
        'dashboard_categories': 'Category Distribution',
        'dashboard_short': 'Short film',
        'dashboard_fiction': 'Fiction',
        'dashboard_users_manage': 'User Management',
        'dashboard_users_see': 'View Users',
        'dashboard_films_manage': 'Film Management',
        'dashboard_films_see': 'View Films',
        'submission_title': 'MarsAI Festival',
        'submission_generation': 'Future Generations',
        'submission_director_info': 'Director Information',
        'submission_civility': 'Civility',
        'submission_mr': 'Mr.',
        'submission_mrs': 'Ms.',
        'submission_other': 'Non-binary',
        'submission_firstname': 'First name *',
        'submission_lastname': 'Last name *',
        'submission_email': 'Email *',
        'submission_phone': 'Mobile *',
        'submission_job': 'Job Title',
        'submission_zip': 'Zip Code',
        'submission_city': 'City',
        'submission_country': 'Country',
        'submission_address': 'Address (Street, number...)',
        'submission_newsletter': 'Subscribe to MarsAI newsletter',
        'submission_film': 'Your Film',
        'submission_title_original': 'Original Title *',
        'submission_title_english': 'English Title',
        'submission_synopsis_original': 'Original Synopsis',
        'submission_synopsis_english': 'English Synopsis',
        'submission_duration': 'Duration (seconds)',
        'submission_language': 'Main language',
        'submission_themes': 'Themes / Tags (ex: Science-fiction, Cyberpunk, Drama, AI...)',
        'submission_hybrid': 'Hybrid',
        'submission_ai_only': '100% AI',
        'submission_ai_tools': 'AI Tools Used (ex: Sora, Runway, Midjourney...)',
        'submission_methodology': 'Methodology (Prompt engineering, process...)',
        'submission_media': 'Media Files',
        'submission_video': 'Film Video (MP4, MOV, AVI, MKV) *',
        'submission_poster': 'Poster (PNG, JPG, WEBP, JPEG) *',
        'submission_subtitles': 'Subtitles (.srt, .vtt)',
        'submission_gallery': 'Image Gallery (Multiple files possible)',
        'submission_collaborators': 'Collaborators',
        'submission_add': '+ Add',
        'submission_submit': 'Submit my film',
        'submission_upload': 'Cloud Upload:',
        'submission_youtube': 'YouTube Finalization...',
        'submission_success': 'Success! Film received and sent to YouTube (ID:',
        'submission_error': 'Error sending.',
        'reset_title': 'RESET-PASSWORD',
        'reset_password': 'Password:',
        'reset_confirm': 'Password confirmation:',
        'reset_button': 'RESET',
        'reset_back': 'Back to login',
        'reset_no_token': 'Token missing from URL.',
        'reset_mismatch': 'Passwords do not match.',
        'reset_success': 'Password reset successfully.',
        'notfound_404': '404',
        'notfound_title': 'Page Not Found',
        'notfound_message': 'The page you are looking for has disappeared into an unknown orbit. Return to the station.',
        'notfound_home': 'Back home',
        'jury_loading': 'Loading film...',
        'jury_not_found': 'Film not found',
        'jury_back': 'Back to selection',
        'jury_official': 'Mars AI Festival — Official Selection',
        'jury_fr': '🇫🇷 FR',
        'jury_en': '🇬🇧 EN',
        'jury_evaluate': 'YOUR EVALUATION',
        'jury_evaluate_desc': 'Rate this film and share your professional opinion',
        'jury_like': 'I Like',
        'jury_discuss': 'To Discuss',
        'jury_dislike': 'I Dislike',
        'jury_comment': 'Comment',
        'jury_optional': '(optional)',
        'jury_comment_placeholder': 'Share your impressions, constructive criticism or remarks about this film...',
        'jury_submit': 'Submit my evaluation',
        'jury_submitting': 'Submitting...',
        'jury_success': 'Vote recorded successfully',
        'jury_saved': 'Your evaluation has been saved',
        'jury_edit': 'Edit my vote',
        'jury_error': 'Unable to load film',
        'gestion_films_title': 'FILMS MANAGEMENT',
        'gestion_films_distribution': 'DISTRIBUTION MOVIES',
        'gestion_films_subtitle': 'Manage all submissions, approve or reject submitted films.',
        'gestion_films_admin_label': 'ADMINISTRATOR',
        'gestion_films_email_label': 'DIRECTOR EMAIL',
        'gestion_films_role_label': 'MODERATOR',
        'gestion_films_column_poster': 'Poster',
        'gestion_films_column_title': 'Title',
        'gestion_films_column_director': 'Director',
        'gestion_films_column_status': 'Status',
        'gestion_films_column_date': 'Date',
        'gestion_films_column_actions': 'Actions',
        'gestion_films_search': 'Search for a film…',
        'gestion_films_all': 'All',
        'gestion_films_valid': 'Valid',
        'gestion_films_pending': 'Pending',
        'gestion_films_refused': 'Refused',
        'gestion_films_loading': 'Loading films...',
        'gestion_films_submitted': 'Film submitted',
        'gestion_films_valid_tag': 'VALID',
        'gestion_films_pending_tag': 'PENDING',
        'gestion_films_refused_tag': 'REFUSED',
        'gestion_films_approve': 'Approve',
        'gestion_films_reject': 'Reject',
        'gestion_films_details': 'Details',
        'gestion_films_page': 'Page',
        'gestion_films_all_selected': 'All films are selected',
        'gestion_films_none_selected': 'No films selected',
        'gestion_films_poster': 'Poster',
        'gestion_films_approved_ok': 'Film approved ✓',
        'gestion_films_rejected_ok': 'Film rejected',
        'gestion_films_featured': 'Film featured',
        'gestion_films_unfeatured': 'Removed from featured',
        'jury_dist_title': 'JURY DISTRIBUTION',
        'jury_dist_subtitle': 'Assign jury members for film evaluation',
        'jury_dist_description': 'Manage jury assignment and their selections for evaluating films.',
        'jury_dist_admin_management': 'Admin Management',
        'jury_dist_admin_label': 'ADMINISTRATOR',
        'jury_dist_email_label': 'EMAIL',
        'jury_dist_role_label': 'ROLE',
        'jury_dist_loading': 'Loading...',
        'competition_anim_title': 'Administrator Space',
        'competition_anim_subtitle': 'Animation Competition',
        'competition_anim_desc': 'Manage selected films and assigned jurors for this category',
        'competition_films': '1. Film Selection',
        'competition_available': 'Available Films',
        'competition_selected': 'Selected Films',
        'competition_all_films_selected': 'All films are selected',
        'competition_no_films': 'No films selected',
        'competition_jury': '2. Jury Assignment',
        'competition_jury_available': 'Available Members',
        'competition_jury_assigned': 'Assigned Jurors',
        'competition_all_jury_assigned': 'All jurors are assigned',
        'competition_no_jury': 'No jurors assigned',
        'jury_management': 'Admin Management',
        'jury_management_title': 'JURY MANAGEMENT',
        'jury_management_desc': 'Jury assignment and their selections for film evaluation.',
        // JuryTab Component Keys
        'jury_form_email_placeholder': 'Email',
        'jury_form_specialty_placeholder': 'Specialty',
        'jury_form_role_jury': 'Jury Member',
        'jury_form_role_lead': 'Jury Leader',
        'jury_form_role_moderator': 'Moderator',
        'jury_add_button': '✅ Add',
        'jury_cancel_button': '✖️ Cancel',
        'jury_unspecified': 'Not specified',
        'jury_progress_label': 'Progress',
        'jury_approved_label': 'Approved',
        'jury_rejected_label': 'Rejected',
        'jury_pending_label': 'To discuss',
        'jury_approval_label': 'Approval',
        'jury_role_leader': '⭐ Leader',
        'jury_role_moderator': '⚖️ Mod',
        'jury_role_member': '📋 Jury',
        'jury_summary_title': '📧 Members Summary',
        'jury_table_name': 'Name',
        'jury_table_role': 'Role',
        'jury_table_progress': 'Progress',
        'jury_table_approved': '✅ Approved',
        'jury_table_rejected': '❌ Rejected',
        'jury_table_approval': 'Approval',
        'jury_role_moderator_full': '⚖️ Moderator',
        'jury_specialty_creative_ai': 'Creative AI',
        'jury_specialty_video_production': 'Video Production',
        'jury_stats_title': 'Global Statistics',
        'jury_jury_members_label': 'Jury Members',
        'jury_films_evaluate_label': 'Films to Evaluate',
        'jury_total_progress_label': 'Total Progress',
        'jury_approved_films_label': 'Approved Films',
        'jury_members_section_title': '👥 Jury Members',
        'jury_add_member_button': '+ Add Member',
        'jury_notes': 'Jury Notes',
        'jury_notes_title': 'Jury Evaluation Notes',
        'jury_notes_subtitle': 'View the evaluations and notes of jury members',
        // Sponsors Page Keys
        'sponsors_title': 'Our Partners',
        'sponsors_intro': 'Mars AI Festival thanks its sponsors for their support in promoting AI-based creativity.',
        'sponsors_gold': 'Gold Sponsors',
        'sponsor_gold_1': 'Gold Sponsor 1',
        'sponsor_gold_1_desc': 'Leader in creative AI solutions',
        'sponsor_gold_2': 'Gold Sponsor 2',
        'sponsor_gold_2_desc': 'Innovators in video technology',
        'sponsors_silver': 'Silver Sponsors',
        'sponsor_silver_1': 'Silver Sponsor 1',
        'sponsor_silver_2': 'Silver Sponsor 2',
        'sponsor_silver_3': 'Silver Sponsor 3',
        'become_sponsor': 'Become a sponsor',
        'become_sponsor_desc': 'Interested in sponsoring Mars AI Festival? Contact us to learn more about partnership opportunities.',
        'contact_us': 'Contact Us',
      }
    };

    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
